name: Terraform Plan (pull_request)

on:
  pull_request:
    branches:
      - '**'

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      TF_VERSION: 1.5.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }} # recommended: use OIDC role
        aws-web-identity-token-file: ${{ secrets.AWS_WEB_IDENTITY_TOKEN_FILE }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra/terraform

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: infra/terraform

    - name: Terraform Plan
      run: terraform plan -input=false -no-color -out=tfplan
      working-directory: infra/terraform

    - name: Save plan artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: infra/terraform/tfplan
